base de données pour les paramètres: 

CREATE DATABASE PARAMETR;

CREATE TABLE PARAMETRE (
    IDPARAM   CHAR (50) PRIMARY KEY,
    ETATPARAM BOOLEAN   NOT NULL
);

INSERT INTO PARAMETRE(IDPARAM, ETATPARAM) VALUES("DELAI_TENTATIVE", TRUE);
INSERT INTO PARAMETRE(IDPARAM, ETATPARAM) VALUES("CHANG_MDP", TRUE);
INSERT INTO PARAMETRE(IDPARAM, ETATPARAM) VALUES("COMPLEX_MDP", TRUE);

base de données pour les clients affaires (nom = CLIENT_AFFAIRE)

CREATE TABLE CLIENT_AFFAIRE (
    IDCLIENT  CHAR (50) PRIMARY KEY,
    NOM       CHAR (50) NOT NULL,
    PRENOM    CHAR (50) NOT NULL,
    MAIL      CHAR (50) NOT NULL,
    TELEPHONE CHAR (50) NOT NULL
);

INSERT INTO CLIENT_AFFAIRE(IDCLIENT, NOM, PRENOM, MAIL, TELEPHONE) VALUES("AFF001", "alice", "nevers", "alice.nevers@gmail.com", "0425421455");
INSERT INTO CLIENT_AFFAIRE(IDCLIENT, NOM, PRENOM, MAIL, TELEPHONE) VALUES("AFF002", "jack", "bauers", "jack.bauers@gmail.com", "0425425514");  
INSERT INTO CLIENT_AFFAIRE(IDCLIENT, NOM, PRENOM, MAIL, TELEPHONE) VALUES("AFF003", "jean", "coutu", "jean.coutu@gmail.com", "0425435514");
INSERT INTO CLIENT_AFFAIRE(IDCLIENT, NOM, PRENOM, MAIL, TELEPHONE) VALUES("AFF004", "wally", "mart", "wally.mart@gmail.com", "0425435614");

base de données pour clients résidentiels (nom = CLIENT_RESID)

CREATE TABLE CLIENT_RESID (
    IDCLIENT  CHAR (50) PRIMARY KEY,
    NOM       CHAR (50) NOT NULL,
    PRENOM    CHAR (50) NOT NULL,
    MAIL      CHAR (50) NOT NULL,
    TELEPHONE CHAR (50) NOT NULL
);

INSERT INTO CLIENT_RESID (IDCLIENT, NOM, PRENOM, MAIL, TELEPHONE) VALUES("RESI001", "mons", "réal", "mons.réal@gmail.com", "0625421455");
INSERT INTO CLIENT_RESID (IDCLIENT, NOM, PRENOM, MAIL, TELEPHONE) VALUES("RESI002", "rosaline", "cosko", "rosaline.cosko@gmail.com", "0625421445");
INSERT INTO CLIENT_RESID (IDCLIENT, NOM, PRENOM, MAIL, TELEPHONE) VALUES("RESI003", "josé", "ontario", "josé.ontario@gmail.com", "0626421445");
INSERT INTO CLIENT_RESID (IDCLIENT, NOM, PRENOM, MAIL, TELEPHONE) VALUES("RESI004", "gimi", "jyro", "gimi.jyro@gmail.com", "0726421445"); 
  
UPDATE PARAMETRE
SET ETATPARAM = FALSE
WHERE IDPARAM = "AFF01";

base utilisateurs 

CREATE TABLE UTILISATEUR (
    ID       CHAR (50)  PRIMARY KEY,
    MDP      CHAR (100) NOT NULL,
    NBR_REST INTEGER
);

INSERT INTO UTILISATEUR (ID, MDP, NBR_REST) VALUES("utilisateur1", "Lbme63$!", 3);
INSERT INTO UTILISATEUR (ID, MDP, NBR_REST) VALUES("utilisateur2", "Lbme64$!", 3);
INSERT INTO UTILISATEUR (ID, MDP, NBR_REST) VALUES("administrateur", "Lbme65$!", 3);

INSERT INTO UTILISATEUR (ID, MDP, NBR_REST) VALUES("utilisateur1", "E0rnG5qhpt8J1dF.cNxeK1", 3);
INSERT INTO UTILISATEUR (ID, MDP, NBR_REST) VALUES("utilisateur2", "6qAkWGqjZHQaLGs3n/0uc/", 3);
INSERT INTO UTILISATEUR (ID, MDP, NBR_REST) VALUES("administrateur", "iMFz3n7aBp0Md.8iAxrYe/", 3);

Lbme63$!
$1$salt$E0rnG5qhpt8J1dF.cNxeK1 
012345678
E0rnG5qhpt8J1dF.cNxeK1

Lbme64$!
$1$salt$6qAkWGqjZHQaLGs3n/0uc/
012345678
6qAkWGqjZHQaLGs3n/0uc/

Lbme65$!
$1$salt$iMFz3n7aBp0Md.8iAxrYe/ 
012345678
iMFz3n7aBp0Md.8iAxrYe/


CREATE TABLE JOURNAL (
    IDJOURNAL   INTEGER   PRIMARY KEY,
    DESCRIPTION CHAR (50) 
);
